# -*- coding: utf-8 -*-
"""01_preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bURg5tXaDmcp47DXlec91xUA2cxjOL9

##Data Preprocessing/Cleaning
"""

import pandas as pd

wage_data = pd.read_csv('Avg_Hourly_Wage_data.csv')
wage_data.head()

USNHPI_data = pd.read_csv('USNHPI_data.csv')
USNHPI_data.head()

len(wage_data)

len(USNHPI_data)

#USNHPI left join wage_data on observation_date
P2_data = pd.merge(wage_data, USNHPI_data)
P2_data.head()
len(P2_data)

#change observation_date column name to date
P2_data = P2_data.rename(columns={'observation_date': 'date', 'CSUSHPINSA': 'USNHPI', 'CES0500000003':'avg_hourly_wage'})
P2_data['date'] = pd.to_datetime(P2_data['date'])
P2_data.head()

#add avg_hourly_wage_lag column
P2_data['avg_hourly_wage_lag'] = P2_data['avg_hourly_wage'].shift(1)

#add avg_hourly_wage_diff column
P2_data['avg_hourly_wage_diff'] = P2_data['avg_hourly_wage'] - P2_data['avg_hourly_wage_lag']

#add USNHPI_diff column
P2_data['USNHPI_diff'] = P2_data['USNHPI'] - P2_data['USNHPI'].shift(1)

P2_data.head()

P2_Data = P2_data
P2_Data.head()

#read out as csv
P2_Data.to_csv('P2_Data.csv', index=False)